apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../components/ingress
configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: frontend-service-configmap
images:
- name: me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo/frontend-service
kind: Kustomization
labels:
- pairs:
    app.kubernetes.io/version: ""
namePrefix: dev-
namespace: dev
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
- path: deployment-add-service-secrets-patch.yaml
  target:
    kind: Deployment
resources:
- ../../base
- service-secrets.yaml
