apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: frontend-service
configMapGenerator:
- name: frontend-service-configmap
  envs:
  - .env
generatorOptions:
  disableNameSuffixHash: true # use a static name
kind: Kustomization
resources:
- deployment.yaml
- service.yaml