apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: frontend-service-podmonitoring
spec:
  selector:
    matchLabels:
      app: frontend-service
  endpoints:
  - interval: 30s
    port: 8080
    path: /metrics
    scheme: http